on: push
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-go@v2
        - run: GOOS=linux GOARCH=arm GOARM=5 go build
        - uses: actions/upload-artifact@v2
          with:
            name: jukebox
            path: jukebox
